### PR TITLE
Added support for touch navigation 

### LINKED ISSUE #12: Does not work on scroll on mobile
I have tested this on chrome android and safari ios,  
scrolling does not change slides.  
``react-fullpage``: ``0.1.16``,
``react version``: ``15.4.1``

### PR DESCRIPTION
**Pull request by m-muhsin**
Swipe up and down to navigate on mobiles and other touch screens. fixes #12

### CODE REVIEW

**Comment by m-muhsin** [comment]
Prevent unwanted scrolling on Firefox.
Fixed: npm run build error on Windows.
Compiled example/bundle.js

**Comment by nickpolet** [comment]
Does this solve the issue of using mac touchpad scrolling too far? On a mac, you end up skipping sections when scrolling down on the touchpad. I've created an issue [here](https://github.com/subtirelumihail/react-fullpage/issues/21).

**Comment by noushad-pp** [comment]
Why isn't this pull request merged till now?

**Comment by MichaelIT** [comment]
It work! tks @m-muhsin

**Comment by 0xpatrickdev** [comment]
Any reason not to accept this pull request?

**Pull request merged**
